services:
  fastapi-app:
    build: .
    container_name: test-jenkins-api-test
    env_file:
      - .env.test
    networks:
      - proxy_net
    restart: unless-stopped

networks:
  proxy_net:
    external: true
