sonar.projectKey=test-jenkins-python-api
sonar.projectName=Test Jenkins Python API
sonar.projectVersion=1.0

sonar.sources=app.py

sonar.tests=tests

sonar.language=py

sonar.exclusions=**/__pycache__/**, **/*.pyc, venv/**, .venv/**, env/**, .env/**, requirements.txt, setup.py
sonar.python.coverage.reportPaths=coverage.xml